### ISSUE TITLE
[bug]-running-win-powershell-v5

### ISSUE THREAD

**Issue by colinwilliams91** [codingMustache/Hack-News-Stories#1]
# Environment
- Win 10 Pro 64bit
- Powershell v5
![image](https://github.com/codingMustache/Hack-News-Stories/assets/92059005/f209a9f0-6df5-42e7-af27-e7791a137200)

# Repro:
- open Powershell
- run `npm i -g hn-cli-reader`
- run `hn-clireader -r`
  - yields error:

# Error:
![image](https://github.com/codingMustache/Hack-News-Stories/assets/92059005/7133d702-44f4-4f30-ab57-2ea0a84897b6)

**Comment by colinwilliams91** [comment]
I think I found the error. The [README How to Use](https://github.com/codingMustache/Hack-News-Stories?tab=readme-ov-file#how-to-use) says: `hn-clireader -RunMode` but the install is `hn-cli-reader`.

I tried running: `hn-cli-reader -r` and it worked:
![image](https://github.com/codingMustache/Hack-News-Stories/assets/92059005/8c11f1f7-d80b-4580-9b4c-99a3f5b975d1)

Just need to fix that typo in the README.

**Comment by codingMustache** [comment]
The `-RunMode` should be replaced withe the run mode you want to run it in. I changed the readme to `-<Run Mode>` to make that a little more clear
