### ISSUE TITLE
[bug]-num-opens-new-term

### ISSUE THREAD

**Issue by colinwilliams91** [codingMustache/Hack-News-Stories#2]
# Environment
- Win 10 Pro 64bit
- Powershell v5
![image](https://github.com/codingMustache/Hack-News-Stories/assets/92059005/f209a9f0-6df5-42e7-af27-e7791a137200)

# Repro:
- open Powershell
- run `hn-cli-reader -r`
- list of articles displays
- press "9"
  - fails to open browser, instead opens a new Command Prompt (not powershell which I had open) with this in the Heading:  
![image](https://github.com/codingMustache/Hack-News-Stories/assets/92059005/6053d119-5210-46c1-be4c-f849292da10c)
  - if i press a different number:
![image](https://github.com/codingMustache/Hack-News-Stories/assets/92059005/45f1f2c7-02e2-4b66-882a-e8f61b0240f0)
  - i think this is a link related to the article i tried to select
- pressing any key to exit still works.

# Error:
![image](https://github.com/codingMustache/Hack-News-Stories/assets/92059005/097e037b-1796-459c-874d-5d7303f8f53c)

**Comment by codingMustache** [comment]
I was using `start` command but I think the right command to open a browser from powershelgl is `Start-Process`, This should be the fixed I just pushed up changes to here and npm. Could you update and test?
